### ISSUE TITLE
Only one cluster in the pcplot result

### ISSUE THREAD

**Issue by boiscat** [karltayeb/ipsc_gp_clustering#2]
Hi, karltayeb, I have an issue with the data set when running pcplot code. In pcplot, I can see only one color (one cluster). I tested sample in 16 timepoints, but the plot just show four of them. After that I checked the PC1 result by:
```def pcplot(model):
    #print(data.set_index(['Gene', 'time']))
    Z = data.set_index(['Gene', 'time']).pivot(columns='line').values 
    Z = Z - np.nanmean(Z, 1)[:, None]
    Z = Z / np.nanstd(Z, 1)[:, None]
    u,s,vh = np.linalg.svd(np.nan_to_num(Z.T), full_matrices=False)
    pc1 = np.squeeze(np.asarray(u[:,0]))
    pc2 = np.squeeze(np.asarray(u[:,1]))
    pc3 = np.squeeze(np.asarray(u[:,3]))
    pc4 = np.squeeze(np.asarray(u[:,4]))
    
    plt.scatter(pc1, pc2, c=model.W1.value.argmax(1))
    print(pc1)
pcplot(model)
```

```
/home/jimmy/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide

/home/jimmy/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
```
I get the rusult with that and PC2 results like PC1.

```
[-0.23987121 -0.23987121 -0.23987121 -0.23987121 -0.23987121 -0.23987121
 -0.22236345 -0.22236345 -0.23987121 -0.22493019 -0.23987121 -0.23987121
 -0.23987121 -0.22493019 -0.23987121 -0.23987121 -0.23987121 -0.22493019
 -0.03649203]
```

The reshaped data format and values like this:
```
line time             Gene     value
0        18489    0  ENSG00000152583 -0.609921
1        18489    0  ENSG00000163918  2.831147
2        18489    0  ENSG00000143498 -0.484112
3        18489    0  ENSG00000102802  1.975052
4        18489    0  ENSG00000188672  2.177993
...        ...  ...              ...       ...
2119825  19209   10  ENSG00000255346 -1.149642
2119826  19209   10  ENSG00000134398 -1.370522
2119827  19209   10  ENSG00000124733  0.108852
2119828  19209   10  ENSG00000104221  0.146564
2119829  19209   10  ENSG00000103266  0.483425
```
Before this error, I tested the data in SplitGPM-ipsc-example.ipynb and got the trajectories with 
K1=2 K2=20 and no error happend.

Do you have any suggestions to solve the problem?

**Comment by zpliu1126** [comment]
It looks like you have successfully run split-GPM. Is it possible to get the versions of TF, GPflow and python that were used?

**Comment by boiscat** [comment]
Yes, I have successfully run the notebook script. Unfortunately, after rebuilding python3, the GPflow package has been removed.

TF version: 2.0
python: 3.7
GPflow: 

I hope it will be useful for you.

**Comment by zpliu1126** [comment]
emmm， how about 

> Yes, I have successfully run the notebook script. Unfortunately, after rebuilding python3, the GPflow package has been removed.
> 
> TF version: 2.0
> python: 3.7
> GPflow:
> 
> I hope it will be useful for you.
wow thank you
what's the version of **GPflow**

**Comment by zpliu1126** [comment]
> Yes, I have successfully run the notebook script. Unfortunately, after rebuilding python3, the GPflow package has been removed.
> 
> TF version: 2.0
> python: 3.7
> GPflow:
> 
> I hope it will be useful for you.

wow thank you very much.
what's the version of ​**GPflow*
